### PR TITLE
Support `{only: true}`

### PR DESCRIPTION
**Pull request by fisker**
ESLint added support for tests with `{only: true}`, see https://github.com/eslint/eslint/pull/14677

### CODE REVIEW

**Comment by fisker** [comment]
@sindresorhus @jfmengels Friendly ping.

**Comment by sindresorhus** [comment]
@fisker It's not a breaking change, correct?

**Comment by fisker** [comment]
I don't think it will break anything.

**Comment by sindresorhus** [comment]
https://github.com/jfmengels/eslint-ava-rule-tester/releases/tag/v4.1.0

**Pull request merged**
