### PR TITLE
support AVA 1 Fixes #7

### LINKED ISSUE #7: Always create unique test titles
AVA 1.0.0 is enforcing unique test titles which causes this module to fail:

```
Uncaught exception in test/filename-case.js

  /Users/sindresorhus/dev/oss/eslint-plugin-unicorn/node_modules/eslint-ava-rule-tester/index.js:12

  Error: Duplicate test title: valid: foo()

  Function.RuleTester.it (node_modules/eslint-ava-rule-tester/index.js:12:5)
  test.valid.forEach.valid (node_modules/eslint-ava-rule-tester/node_modules/eslint/lib/testers/rule-tester.js:546:32)
  Function.RuleTester.describe (node_modules/eslint-ava-rule-tester/node_modules/eslint/lib/testers/rule-tester.js:545:28)
  Function.RuleTester.describe (node_modules/eslint-ava-rule-tester/index.js:8:19)
  Function.RuleTester.describe (node_modules/eslint-ava-rule-tester/node_modules/eslint/lib/testers/rule-tester.js:544:24)
  Function.RuleTester.describe (node_modules/eslint-ava-rule-tester/index.js:8:19)
  RuleTester.run (node_modules/eslint-ava-rule-tester/node_modules/eslint/lib/testers/rule-tester.js:543:20)
```

I guess just adding `#n` (e.g. `#1`) at the end of the title would be sufficient.

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@jfmengels this PR also moves eslint to a peerDep because without it I was not running eslint-plugin-lodash-fp tests with the correct version of eslint and so I didn't spot a test failure

**Comment by jfmengels** [comment]
I just released this in v3.0.0.
Thanks a lot for working on this, and sorry that it took so long for me to handle this.

I'm still feeling a bit burnt-out by open-source, but I'll try to be more responsive next time you call me out (for this repo and others). (Also, let me know if there are repos/issues for which you're waiting for something from me).

I've invited @graingert and @sindresorhus, so that this does not get left behind.
Thanks again, and sorry again! I hope this solves some of your problems :)

**Comment by graingert** [comment]
Can you add me to the npm publish access too?

**Comment by jfmengels** [comment]
Yes, I gave it to you at the same time.

**Comment by graingert** [comment]
Awesome thanks

**Comment by sindresorhus** [comment]
@graingert This is not working when I run multiple `avaRuleTester` instances in one file using different names. It seems the `ruleTester.run()` name is not being used. See: https://github.com/avajs/eslint-plugin-ava/commit/2ccc13bb8103accb706b470b8691a887c7dbc0d4#diff-e47aa84a4524f11b9fd4e8f77ef07081R15

**Pull request merged**
